from models.unet_architecture.unet_plain import UNet
from models.unet_architecture.unet_extra_skip import UNetExtraSkip

from models.unet_architecture.multiframe_unet import MultiFrameUNet
from models.unet_architecture.multiframe_unet_extra_skip import MultiFrameUNetExtraSkip